import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogTitle,
  DialogTrigger,
} from '../ui/dialog';
import { Separator } from '../ui/separator';

const INSTRUCTIONS_T0_FOLLOW = [
  {
    title: 'Video Selection',
    description:
      'Select the video you want to classify but the size should be less than 6MB',
  },
  {
    title: 'Be Careful with the video',
    description:
      'Video should be clear and should not contain any nudity or violence. Video only contain one person.',
  },
  {
    title: 'Get the results 🎉',
    description:
      'Get the results of the video in a few seconds. And you are done! Dont forget to share the results with your friends.',
  },
];

const ClassificationInstModal = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <Dialog>
      <DialogTrigger>{children}</DialogTrigger>
      <DialogContent>
        <div className="space-y-1">
          <DialogTitle>Please follow the instructions</DialogTitle>
          <p className="text-sm text-muted-foreground">
            Follow the following instructions to get the best results:
          </p>
        </div>

        <div>
          {INSTRUCTIONS_T0_FOLLOW.map((instruction, index) => (
            <div key={index} className="flex items-center gap-4 space-y-5">
              <div className="flex-shrink-0 w-8 h-8 flex items-center justify-center rounded-full bg-primary/10">
                {index + 1}
              </div>
              <div>
                <h3 className="font-semibold text-primary">
                  {instruction.title}
                </h3>
                <p className="text-sm">{instruction.description}</p>
              </div>
            </div>
          ))}
          <Separator className="mt-6" />
          <div className="mt-6">
            <p className="text-sm">
              <strong className="text-primary">Note:</strong> If you don&apos;t
              follow the instructions, you might not get the best results.
            </p>
          </div>

          <div className="mt-4">
            <p className="text-sm">
              <strong className="text-primary">Disclaimer:</strong> We are not
              responsible for any misuse of the results. The results are
              generated by the AI model and should be used for educational
              purposes only.
            </p>
          </div>

          <div className="mt-4">
            <p className="text-sm">
              <strong className="text-primary">Privacy:</strong> We don&apos;t
              store your video or any information. Everything is done on the
              client side.
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default ClassificationInstModal;
